#!/bin/sh

# http://tbaggery.com/2011/08/08/effortless-ctags-with-git.html
# vimrc
if [ -f Gemfile ]
  then
  # set -e
  # PATH="/usr/local/bin:$PATH"
  # trap "rm -f .git/tags.$$" EXIT
  # `brew --prefix`/bin/ctags --tag-relative -Rf.git/tags.$$ --exclude=tmp  --exclude=.git --exclude=log . `bundle show --paths`
  # mv .git/tags.$$ .git/tags
  # https://github.com/phstc/dotfiles/blob/master/bashrc#git_template_hooks_init

  `brew --prefix`/bin/ctags --tag-relative -Rf.git/tags --exclude=tmp  --exclude=.git --exclude=log . `bundle show --paths`
fi
